import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, ChevronRight, Clock3, Radio, ShieldAlert, Siren, Wifi } from "lucide-react";
import { useMemo } from "react";
import { Link } from "wouter";

const severityStyles = { critical: "border-red-400/30 bg-red-400/10 text-red-300", error: "border-orange-400/30 bg-orange-400/10 text-orange-300", warning: "border-amber-400/30 bg-amber-400/10 text-amber-300", info: "border-sky-400/30 bg-sky-400/10 text-sky-300" } as const;
const formatRelative = (value: Date | string) => { const diff = Math.max(0, Date.now() - new Date(value).getTime()); const minutes = Math.floor(diff / 60000); if (minutes < 1) return "just now"; if (minutes < 60) return `${minutes}m ago`; return `${Math.floor(minutes / 60)}h ago`; };

export default function Dashboard() {
  const alertInput = useMemo(() => ({ limit: 100 }), []);
  const incidentInput = useMemo(() => ({ limit: 50 }), []);
  const alertsQuery = trpc.alerts.list.useQuery(alertInput, { refetchInterval: 5000, staleTime: 3000 });
  const incidentsQuery = trpc.incidents.list.useQuery(incidentInput, { refetchInterval: 7000, staleTime: 5000 });
  const metricsQuery = trpc.metrics.analytics.useQuery({ period: "24h" }, { refetchInterval: 15000, staleTime: 10000 });
  const utils = trpc.useUtils();
  const updateAlert = trpc.alerts.updateStatus.useMutation({ onSuccess: () => utils.alerts.list.invalidate() });
  const updateIncident = trpc.incidents.updateStatus.useMutation({ onSuccess: () => { utils.incidents.list.invalidate(); utils.metrics.analytics.invalidate(); } });
  const alerts = alertsQuery.data ?? [];
  const incidents = incidentsQuery.data ?? [];
  const activeIncidents = incidents.filter(incident => incident.status !== "resolved");
  const severityCounts = ["critical", "error", "warning", "info"].map(severity => ({ severity, count: alerts.filter(alert => alert.severity === severity).length }));
  const isLoading = alertsQuery.isLoading || incidentsQuery.isLoading;

  return <DashboardLayout><div className="min-h-[calc(100vh-2rem)] bg-[#090d14] text-slate-100 -m-4 p-5 md:p-7"><div className="mx-auto max-w-[1520px] space-y-6">
    <header className="flex flex-col gap-4 border-b border-white/8 pb-6 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.24em] text-cyan-300/80"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_12px_#67e8f9]" />Signal control plane</div><h1 className="text-3xl font-semibold tracking-tight text-white md:text-4xl">Incident operations</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Correlate production noise, inspect probable root causes, and move from first signal to recovery with less context switching.</p></div><div className="flex items-center gap-3 text-xs text-slate-400"><div className="flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/8 px-3 py-2 text-emerald-300"><Wifi className="h-3.5 w-3.5" /> Live polling</div><span>updated {formatRelative(new Date())}</span></div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Active incidents", value: activeIncidents.length, icon: Siren, tone: "text-red-300", note: "requires attention" }, { label: "Alerts in window", value: metricsQuery.data?.totals.alerts ?? alerts.length, icon: Radio, tone: "text-cyan-300", note: "rolling 24 hours" }, { label: "Critical signals", value: severityCounts[0].count, icon: ShieldAlert, tone: "text-orange-300", note: "highest priority" }, { label: "MTTR", value: metricsQuery.data?.totals.mttrMinutes ? `${metricsQuery.data.totals.mttrMinutes}m` : "—", icon: Clock3, tone: "text-violet-300", note: "resolved incidents" }].map(item => <Card key={item.label} className="border-white/8 bg-[#101722] shadow-[0_12px_38px_rgba(0,0,0,.18)]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{item.label}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-white">{isLoading ? <Skeleton className="h-9 w-16 bg-white/10" /> : item.value}</p><p className="mt-2 text-xs text-slate-500">{item.note}</p></div><item.icon className={`h-5 w-5 ${item.tone}`} /></div></CardContent></Card>)}</section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.65fr)]"><Card className="overflow-hidden border-white/8 bg-[#101722]"><CardHeader className="border-b border-white/8 pb-4"><div className="flex items-center justify-between"><div><CardTitle className="text-base text-white">Active incidents</CardTitle><p className="mt-1 text-xs text-slate-500">Clusters are recomputed as new alerts arrive.</p></div><Link href="/incidents" className="flex items-center gap-1 text-xs font-medium text-cyan-300 hover:text-cyan-200">View all <ArrowUpRight className="h-3.5 w-3.5" /></Link></div></CardHeader><CardContent className="p-0"><div className="divide-y divide-white/6">{activeIncidents.length === 0 && !isLoading ? <EmptyState icon={CheckCircle2} title="No active incidents" detail="New correlated signals will appear here." /> : activeIncidents.slice(0, 6).map(incident => <div key={incident.id} className="group flex items-center gap-4 px-5 py-4 transition-colors hover:bg-white/[.025]"><div className={`mt-0.5 h-2 w-2 shrink-0 rounded-full ${incident.severity === "critical" ? "bg-red-400 shadow-[0_0_12px_#f87171]" : incident.severity === "error" ? "bg-orange-400" : "bg-amber-300"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Link href={`/incidents/${incident.id}`} className="truncate text-sm font-medium text-slate-100 hover:text-cyan-300">{incident.title}</Link><Badge variant="outline" className={`h-5 border text-[10px] uppercase ${severityStyles[incident.severity]}`}>{incident.severity}</Badge></div><p className="mt-1 truncate text-xs text-slate-500">{incident.aiExplanation ?? incident.description ?? "RCA pending"}</p></div><div className="hidden text-right sm:block"><p className="text-xs text-slate-400">{incident.alerts.length} alerts</p><p className="mt-1 text-[11px] text-slate-600">{formatRelative(incident.updatedAt)}</p></div><Button variant="ghost" size="icon" className="h-8 w-8 text-slate-500 hover:bg-white/8 hover:text-white" onClick={() => updateIncident.mutate({ id: incident.id, status: "acknowledged" })}><ChevronRight className="h-4 w-4" /></Button></div>)}</div></CardContent></Card>
    <Card className="border-white/8 bg-[#101722]"><CardHeader className="pb-3"><CardTitle className="text-base text-white">Severity heatmap</CardTitle><p className="mt-1 text-xs text-slate-500">Signals received in the live window.</p></CardHeader><CardContent className="space-y-3">{severityCounts.map(item => <div key={item.severity} className="flex items-center gap-3"><div className={`flex h-9 w-9 items-center justify-center rounded-lg border ${severityStyles[item.severity as keyof typeof severityStyles]}`}><AlertTriangle className="h-4 w-4" /></div><div className="flex-1"><div className="flex justify-between text-xs"><span className="capitalize text-slate-300">{item.severity}</span><span className="font-mono text-slate-500">{item.count}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/6"><div className={`h-full rounded-full ${item.severity === "critical" ? "bg-red-400" : item.severity === "error" ? "bg-orange-400" : item.severity === "warning" ? "bg-amber-300" : "bg-sky-400"}`} style={{ width: `${Math.min(100, Math.max(4, item.count * 12))}%` }} /></div></div></div>)}<div className="mt-5 rounded-lg border border-dashed border-white/10 bg-white/[.02] p-3 text-xs text-slate-500"><span className="font-mono text-cyan-300">{alerts.length}</span> total signals are being watched across <span className="font-mono text-cyan-300">{new Set(alerts.map(alert => alert.source)).size}</span> sources.</div></CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><Card className="border-white/8 bg-[#101722]"><CardHeader className="pb-3"><CardTitle className="text-base text-white">Cluster overview</CardTitle><p className="mt-1 text-xs text-slate-500">Similarity groups surfaced from alert embeddings.</p></CardHeader><CardContent className="space-y-2">{activeIncidents.slice(0, 5).map(incident => <Link key={incident.id} href={`/incidents/${incident.id}`} className="flex items-center gap-3 rounded-lg border border-white/6 bg-white/[.02] p-3 transition hover:border-cyan-300/30 hover:bg-cyan-300/[.03]"><div className="flex h-8 w-8 items-center justify-center rounded-md bg-cyan-300/10 text-cyan-300"><Activity className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm text-slate-200">{incident.title}</p><p className="mt-1 text-xs text-slate-500">{incident.cluster?.similarity ?? 0}% similarity · {incident.alerts.length} members</p></div><ChevronRight className="h-4 w-4 text-slate-600" /></Link>)}{activeIncidents.length === 0 && <EmptyState icon={Activity} title="Waiting for clusters" detail="Ingest an alert to create the first similarity group." />}</CardContent></Card>
    <Card className="border-white/8 bg-[#101722]"><CardHeader className="pb-3"><div className="flex items-center justify-between"><div><CardTitle className="text-base text-white">Live alert feed</CardTitle><p className="mt-1 text-xs text-slate-500">Newest signals, polled every 5 seconds.</p></div><div className="flex items-center gap-1 text-[10px] uppercase tracking-widest text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" /> streaming</div></div></CardHeader><CardContent className="space-y-2">{alerts.slice(0, 5).map(alert => <div key={alert.id} className="flex items-start gap-3 rounded-lg border border-white/6 p-3"><div className={`mt-1 h-2 w-2 shrink-0 rounded-full ${alert.severity === "critical" ? "bg-red-400" : alert.severity === "error" ? "bg-orange-400" : alert.severity === "warning" ? "bg-amber-300" : "bg-sky-400"}`} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-medium text-slate-300">{alert.source}</p><span className="shrink-0 text-[11px] text-slate-600">{formatRelative(alert.timestamp)}</span></div><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-slate-500">{alert.message}</p><div className="mt-2 flex items-center justify-between"><Badge variant="outline" className={`h-5 border text-[10px] uppercase ${severityStyles[alert.severity]}`}>{alert.severity}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6 px-2 text-[10px] text-slate-500 hover:text-emerald-300" onClick={() => updateAlert.mutate({ id: alert.id, status: "acknowledged" })}>Ack</Button><Button variant="ghost" size="sm" className="h-6 px-2 text-[10px] text-slate-500 hover:text-cyan-300" onClick={() => updateAlert.mutate({ id: alert.id, status: "resolved" })}>Resolve</Button></div></div></div></div>)}{alerts.length === 0 && <EmptyState icon={Radio} title="No alerts received" detail="POST an alert to /api/v1/alerts to start the feed." />}</CardContent></Card></div>
  </div></div></DashboardLayout>;
}

function EmptyState({ icon: Icon, title, detail }: { icon: typeof Activity; title: string; detail: string }) { return <div className="flex flex-col items-center justify-center py-12 text-center"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-white/5 text-slate-500"><Icon className="h-5 w-5" /></div><p className="text-sm text-slate-300">{title}</p><p className="mt-1 max-w-xs text-xs leading-relaxed text-slate-600">{detail}</p></div>; }
